### ISSUE TITLE
启动fish-speech-ziming服务的时候报错，提示显卡驱动未安装，实际已经安装

### ISSUE THREAD

**Issue by fanhua0401** [GuijiAI/HeyGem.ai#150]
![Image](https://github.com/user-attachments/assets/b5186f53-b7ad-41da-8f38-71ab74fdf19c)
![Image](https://github.com/user-attachments/assets/d8091e6e-c404-40fb-acce-d0d07c10c11f)
![Image](https://github.com/user-attachments/assets/4b4c4f90-e47f-4d7e-b374-2524da63e4f8)

**Comment by fanhua0401** [comment]
![Image](https://github.com/user-attachments/assets/dc7da13a-87aa-4384-8285-5c83d78f5221)

**Comment by whl88** [comment]
Please execute "nvidia - smi" inside the container to check if there is a graphics card.

**Comment by fanhua0401** [comment]
> Please execute "nvidia - smi" inside the container to check if there is a graphics card.

上面的截图就是nvidia - smi命令的结果，看起来没有异常

**Comment by whl88** [comment]
execute "nvidia-smi" **inside the container** `heygem-tts`

**Comment by whl88** [comment]
Try adding the following section of configuration.

![Image](https://github.com/user-attachments/assets/369ddadb-d03b-4b14-b61b-f78fa201399c)

```
deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
