### ISSUE TITLE
f2f容器启动失败，报错网络连不上

### ISSUE THREAD

**Issue by wingchi-leung** [GuijiAI/HeyGem.ai#55]
![Image](https://github.com/user-attachments/assets/9370f85d-3646-430a-a47a-36ba6e7c9b8f) 

025-03-09 21:46:30 Call stack:
2025-03-09 21:46:30   File "/code/app_local.py", line 230, in <module>
2025-03-09 21:46:30     a()
2025-03-09 21:46:30 Message: '网络连接出现问题, 正在尝试再次请求: '
2025-03-09 21:46:30 Arguments: (2,)
2025-03-09 21:46:30 [2025-03-09 21:46:30] [app_local.py[line:230]] [ERROR] [第[3]次回调异常报错:Invalid URL '/active': No scheme supplied. Perhaps you meant https:///active?]
2025-03-09 21:46:30 --- Logging error ---
2025-03-09 21:46:30 Traceback (most recent call last):
2025-03-09 21:46:30   File "request_utils.py", line 27, in request_utils.request_post
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 115, in post
2025-03-09 21:46:30     return request("post", url, data=data, json=json, **kwargs)
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 59, in request
2025-03-09 21:46:30     return session.request(method=method, url=url, **kwargs)
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
2025-03-09 21:46:30     prep = self.prepare_request(req)
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
2025-03-09 21:46:30     p.prepare(
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/site-packages/requests/models.py", line 368, in prepare
2025-03-09 21:46:30     self.prepare_url(url, params)
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/site-packages/requests/models.py", line 439, in prepare_url
2025-03-09 21:46:30     raise MissingSchema(
2025-03-09 21:46:30 requests.exceptions.MissingSchema: Invalid URL '/active': No scheme supplied. Perhaps you meant https:///active?
2025-03-09 21:46:30 
2025-03-09 21:46:30 During handling of the above exception, another exception occurred:
2025-03-09 21:46:30 
2025-03-09 21:46:30 Traceback (most recent call last):
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/logging/__init__.py", line 1085, in emit
2025-03-09 21:46:30     msg = self.format(record)
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/logging/__init__.py", line 929, in format
2025-03-09 21:46:30     return fmt.format(record)
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/logging/__init__.py", line 668, in format
2025-03-09 21:46:30     record.message = record.getMessage()
2025-03-09 21:46:30   File "/usr/local/python3/lib/python3.8/logging/__init__.py", line 373, in getMessage
2025-03-09 21:46:30     msg = msg % self.args
2025-03-09 21:46:30 TypeError: not all arguments converted during string formatting
2025-03-09 21:46:30 Call stack:
2025-03-09 21:46:30   File "/code/app_local.py", line 230, in <module>
2025-03-09 21:46:30     a()
2025-03-09 21:46:30 Message: '网络连接出现问题, 正在尝试再次请求: '
2025-03-09 21:46:30 Arguments: (3,)

这是我的compose.yaml，基本上是用官方的，就是有一些依赖改成了国内的源，电脑挂了代理，端口也是通的。 排查是里面的代码抛得异常，没辙了，求格外大佬帮忙看看 🙏...  
``` yaml
 networks:
  ai_network:
    driver: bridge

services:
  heygem-tts:
    image: guiji2025/fish-speech-ziming:1.0.39
    container_name: heygem-tts
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - NO_PROXY=localhost,127.0.0.1
    ports:
      - '18180:8080'
    volumes:
      - d:/heygem_data/voice/data:/code/data
      - d:/heygem_data/voice/config.py:/code/config.py
    command: /bin/bash -c "cd /code && /opt/conda/envs/python310/bin/pip install -i https://pypi.tuna.tsinghua.edu.cn/simple ormsgpack~=1.5.0  && /opt/conda/envs/python310/bin/pip install -r requirements.txt && /opt/conda/envs/python310/bin/python3 -m tools.api --listen 0.0.0.0:8080"
    networks:
      - ai_network



  heygem-f2f:
    image: guiji2025/heygem.ai:0.0.7_sdk_slim
    container_name: heygem-f2f
    restart: always
    privileged: true
    volumes:
      - d:/heygem_data/face2face:/code/data
      - d:/heygem_data/face2face/sdk/config.ini:/code/config/config.ini
      - d:/heygem_data/face2face/sdk/license.txt:/code/license.txt
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=http://127.0.0.1:7890
      - NO_PROXY=localhost,127.0.0.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network

  heygem-asr:
    image: guiji2025/fun-asr:1.0.1
    container_name: heygem-asr
    restart: always
    runtime: nvidia
    privileged: true
    working_dir: /workspace/FunASR/runtime
    ports:
      - '10095:10095'
    volumes:
      - D:/heygem_data/asr/runtime-resources/models:/workspace/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ai_network

```
